import * as stylex from "@stylexjs/stylex";

import { colors, fonts, media, motion, radii } from "../styles/tokens.stylex";

const messageEnter = stylex.keyframes({
  from: { opacity: 0, transform: "translateY(3px)" },
  to: { opacity: 1, transform: "translateY(0)" },
});

const dotWave = stylex.keyframes({
  "0%, 70%, 100%": { opacity: 0.24 },
  "35%": { opacity: 0.9 },
});

export const transientStyles = stylex.create({
  notification: {
    position: "absolute",
    zIndex: 1,
    bottom: "calc(100% + 8px)",
    left: "50%",
    width: "max-content",
    maxWidth: "min(480px, calc(100vw - 24px))",
    minHeight: 32,
    padding: "7px 10px",
    alignItems: "center",
    columnGap: 6,
    rowGap: 1,
    color: colors.mutedForeground,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: { default: colors.border, [media.forcedColors]: "Highlight" },
    borderRadius: radii.control,
    boxShadow: colors.shadow,
    pointerEvents: "none",
    opacity: { default: 1, "@starting-style": 0 },
    transform: {
      default: "translateX(-50%)",
      "@starting-style": "translate(-50%, 3px)",
      [media.reducedMotion]: "none",
    },
    transitionProperty: "opacity, transform",
    transitionDuration: { default: "160ms", [media.reducedMotion]: "120ms" },
    transitionTimingFunction: { default: motion.easeOut, [media.reducedMotion]: "linear" },
  },
  receipt: {
    display: "grid",
    gridTemplateColumns: "14px auto minmax(0, 1fr)",
    margin: 0,
    font: "inherit",
    textAlign: "left",
    cursor: "pointer",
    pointerEvents: "auto",
    backgroundColor: {
      default: colors.surface,
      [media.hover]: {
        ":hover": `color-mix(in srgb, ${colors.foreground} 6%, ${colors.surface})`,
      },
    },
    outline: { ":focus-visible": `2px solid ${colors.focus}` },
    outlineOffset: { ":focus-visible": 2 },
  },
  receiptInline: {
    position: "static",
    width: "100%",
    maxWidth: "none",
    backgroundColor: colors.surfaceSubtle,
    boxShadow: "none",
    transform: "none",
  },
  notificationIcon: {
    gridColumn: 1,
    gridRow: 1,
    color: { default: colors.primary, [media.forcedColors]: "Highlight" },
  },
  receiptIcon: {
    color: colors.foreground,
  },
  receiptLabel: {
    gridColumn: 2,
    gridRow: 1,
    color: colors.foreground,
    fontFamily: fonts.mono,
    fontSize: 10,
    fontWeight: 600,
  },
  receiptStatus: {
    gridColumn: 3,
    gridRow: 1,
    color: colors.foreground,
    fontSize: 12,
    fontWeight: 600,
  },
  receiptSummary: {
    gridColumn: "2 / 4",
    gridRow: 2,
    minWidth: 0,
    color: colors.mutedForeground,
    fontSize: 11,
    lineHeight: "14px",
    overflowWrap: "anywhere",
  },
  attention: {
    position: "fixed",
    inset: 0,
    pointerEvents: "none",
    opacity: { default: 1, "@starting-style": 0 },
    transitionProperty: "opacity",
    transitionDuration: { default: "180ms", [media.reducedMotion]: "0ms" },
    transitionTimingFunction: motion.easeOut,
    transform: { [media.reducedMotion]: "none" },
  },
  activity: {
    transitionDuration: { default: "120ms", [media.reducedMotion]: "0ms" },
  },
  exiting: {
    opacity: 0,
  },
  ring: {
    position: "fixed",
    zIndex: 1,
    backgroundColor: {
      default: `color-mix(in srgb, ${colors.primary} 2%, transparent)`,
      [media.forcedColors]: "transparent",
    },
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: { default: colors.primary, [media.forcedColors]: "Highlight" },
    borderRadius: 10,
    "::after": {
      position: "absolute",
      inset: -4,
      borderWidth: 3,
      borderStyle: "solid",
      borderColor: {
        default: `color-mix(in srgb, ${colors.primary} 12%, transparent)`,
        [media.forcedColors]: "Highlight",
      },
      borderRadius: 13,
      content: "",
    },
  },
  attentionLabel: {
    position: "fixed",
    zIndex: 6,
    display: "grid",
    width: "max-content",
    maxWidth: "min(480px, calc(100vw - 24px))",
    minHeight: 28,
    padding: "5px 8px 6px 6px",
    alignItems: "center",
    gridTemplateColumns: "14px minmax(0, 1fr) auto",
    columnGap: 6,
    rowGap: 1,
    color: { default: colors.foreground, [media.forcedColors]: "CanvasText" },
    backgroundColor: { default: colors.surface, [media.forcedColors]: "Canvas" },
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: { default: colors.primary, [media.forcedColors]: "Highlight" },
    borderRadius: radii.control,
    fontSize: 12,
    fontWeight: 500,
    lineHeight: "16px",
    transform: {
      "@starting-style": "translateY(2px)",
      [media.reducedMotion]: "none",
    },
    transitionProperty: "opacity, transform",
    transitionDuration: { default: "160ms", [media.reducedMotion]: "0ms" },
    transitionTimingFunction: motion.easeOut,
  },
  attentionStatus: {
    gridColumn: 2,
    gridRow: 1,
    minWidth: 0,
    fontWeight: 600,
    overflowWrap: "anywhere",
  },
  attentionMessage: {
    gridColumn: "2 / 4",
    gridRow: 2,
    minWidth: 0,
    color: colors.mutedForeground,
    fontSize: 11,
    lineHeight: "14px",
    overflowWrap: "anywhere",
    whiteSpace: "pre-wrap",
    animationName: { default: messageEnter, [media.reducedMotion]: "none" },
    animationDuration: "160ms",
    animationTimingFunction: motion.easeOut,
  },
  target: {
    gridColumn: 3,
    gridRow: 1,
    color: colors.mutedForeground,
    fontFamily: fonts.mono,
    fontSize: 10,
    fontWeight: 600,
  },
  notice: {
    zIndex: 3,
    display: "grid",
    gridTemplateColumns: "14px minmax(0, 1fr) auto",
    color: { default: colors.mutedForeground, [media.forcedColors]: "CanvasText" },
    backgroundColor: { default: colors.surface, [media.forcedColors]: "Canvas" },
    boxShadow: "none",
    backdropFilter: "none",
    transitionDuration: { default: "180ms", [media.reducedMotion]: "0ms" },
  },
  revealNotice: {
    transitionDelay: "400ms",
  },
  exitingNotice: {
    transitionDelay: "0ms",
  },
  noticeStatus: {
    gridColumn: 2,
    gridRow: 1,
    color: colors.foreground,
    fontSize: 12,
    fontWeight: 600,
  },
  noticeMessage: {
    gridColumn: "2 / 4",
    gridRow: 2,
    minWidth: 0,
    fontSize: 11,
    lineHeight: "14px",
    overflowWrap: "anywhere",
    whiteSpace: "pre-wrap",
  },
  working: {
    width: 14,
    height: 14,
    color: { [media.forcedColors]: "Highlight" },
  },
  workingDot: {
    opacity: { default: 0.24, [media.reducedMotion]: 0.35 },
    animationName: { default: dotWave, [media.reducedMotion]: "none" },
    animationDuration: "1.2s",
    animationTimingFunction: "ease-in-out",
    animationIterationCount: "infinite",
  },
  workingDotCenter: {
    opacity: { default: 0.24, [media.reducedMotion]: 0.9 },
  },
  trail: {
    display: "inline-flex",
    gridColumn: 3,
    gridRow: 1,
    height: 16,
    alignItems: "center",
    gap: 2,
    color: colors.mutedForeground,
    pointerEvents: "auto",
  },
  trailButton: {
    width: 18,
    height: 16,
    minHeight: 0,
    padding: 0,
    borderRadius: 3,
    color: "inherit",
  },
  trailButtonDisabled: {
    opacity: 0.4,
    cursor: "default",
  },
  trailCount: {
    padding: "0 2px",
    fontFamily: fonts.mono,
    fontSize: 10,
    lineHeight: "16px",
    whiteSpace: "nowrap",
  },
});
