import * as stylex from "@stylexjs/stylex";

import { colors, fonts, media, radii } from "../../styles/tokens.stylex";

export const overlayStyles = stylex.create({
  overlay: {
    position: "fixed",
    inset: 0,
    pointerEvents: "none",
  },
  fixedAnchor: {
    position: "fixed",
    pointerEvents: "none",
  },
  outputHighlight: {
    backgroundColor: `color-mix(in srgb, ${colors.primary} 3%, transparent)`,
    borderWidth: 1,
    borderStyle: "dashed",
    borderColor: { default: colors.primary, [media.forcedColors]: "Highlight" },
    borderRadius: radii.label,
  },
  anchorPreview: {
    zIndex: 2,
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: { default: colors.primary, [media.forcedColors]: "Highlight" },
    boxShadow: `0 0 0 1px ${colors.surface}`,
  },
  anchorPoint: {
    width: 14,
    height: 14,
    backgroundColor: colors.primary,
    borderRadius: "50%",
    transform: "translate(-50%, -50%)",
  },
  anchorRect: {
    backgroundColor: `color-mix(in srgb, ${colors.primary} 9%, transparent)`,
    borderRadius: 4,
  },
  marker: {
    touchAction: "none",
    userSelect: "none",
    opacity: { default: 1, ":disabled": 1 },
    borderColor: { [media.forcedColors]: "Highlight" },
  },
  markerBlocked: {
    pointerEvents: "none",
  },
  point: {
    position: "fixed",
    zIndex: 3,
    minWidth: 30,
    height: 24,
    padding: "0 6px",
    pointerEvents: "auto",
    color: colors.accentForeground,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: colors.primary,
    borderRadius: radii.label,
    boxShadow: "0 1px 3px rgb(15 23 42 / 14%)",
    fontFamily: fonts.mono,
    fontSize: 10,
    fontWeight: 600,
    transform: "translate(-50%, -50%)",
    "::before": {
      position: { [media.coarsePointer]: "absolute" },
      inset: { [media.coarsePointer]: -10 },
      content: { [media.coarsePointer]: "" },
    },
  },
  pointCurrent: {
    color: colors.onPrimary,
    backgroundColor: colors.primaryHover,
    boxShadow: "0 1px 3px rgb(15 23 42 / 18%)",
  },
  rectContainer: {
    position: "fixed",
    zIndex: 3,
    pointerEvents: "none",
  },
  rect: {
    position: "absolute",
    inset: 0,
    minWidth: 22,
    minHeight: 22,
    padding: 0,
    pointerEvents: "auto",
    backgroundColor: `color-mix(in srgb, ${colors.primary} 3%, transparent)`,
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: colors.primary,
    borderRadius: radii.label,
  },
  rectCurrent: {
    borderWidth: 2,
  },
  rectLabel: {
    position: "absolute",
    top: -25,
    left: -1,
    minWidth: 30,
    height: 22,
    padding: "3px 6px",
    color: colors.accentForeground,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: colors.primary,
    borderRadius: radii.label,
    fontFamily: fonts.mono,
    fontSize: 10,
    fontWeight: 600,
  },
  rectLabelCurrent: {
    color: colors.onPrimary,
    backgroundColor: colors.primaryHover,
  },
  busy: {
    opacity: 0.6,
  },
  capturing: {
    "::after": {
      position: "absolute",
      right: -4,
      bottom: -4,
      width: 8,
      height: 8,
      backgroundColor: colors.surface,
      borderWidth: 2,
      borderStyle: "solid",
      borderColor: colors.primary,
      borderRadius: "50%",
      content: "",
    },
  },
  resizeHandle: {
    position: "absolute",
    zIndex: 2,
    width: 12,
    height: 12,
    padding: 0,
    pointerEvents: "auto",
    touchAction: "none",
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: { default: colors.primary, [media.forcedColors]: "Highlight" },
    borderRadius: 2,
    boxShadow: "0 1px 3px rgb(15 23 42 / 16%)",
    "::after": {
      position: "absolute",
      inset: { default: -6, [media.coarsePointer]: -13 },
      content: "",
    },
  },
  nw: {
    top: 0,
    left: 0,
    cursor: "nwse-resize",
    transform: "translate(-50%, -50%)",
  },
  ne: {
    top: 0,
    right: 0,
    cursor: "nesw-resize",
    transform: "translate(50%, -50%)",
  },
  sw: {
    bottom: 0,
    left: 0,
    cursor: "nesw-resize",
    transform: "translate(-50%, 50%)",
  },
  se: {
    right: 0,
    bottom: 0,
    cursor: "nwse-resize",
    transform: "translate(50%, 50%)",
  },
});
