import * as stylex from "@stylexjs/stylex";

import { colors, fonts, media, radii } from "../../styles/tokens.stylex";

export const sheetStyles = stylex.create({
  sheet: {
    position: "relative",
    inset: "auto",
    display: "flex",
    width: "100%",
    maxHeight: "inherit",
    overflow: "hidden",
    flexDirection: "column",
    color: colors.foreground,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: colors.border,
    borderRadius: radii.surface,
    boxShadow: colors.shadow,
    pointerEvents: "auto",
  },
  header: {
    display: "flex",
    minHeight: 42,
    padding: "7px 8px 2px 14px",
    alignItems: "center",
    justifyContent: "space-between",
  },
  identity: {
    display: "flex",
    minWidth: 0,
    alignItems: "center",
    gap: 6,
  },
  title: {
    margin: 0,
    color: colors.foreground,
    fontSize: 14,
    fontWeight: 600,
    lineHeight: 1.25,
  },
  actions: {
    display: "flex",
    alignItems: "center",
    gap: 2,
  },
  tabs: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    minHeight: 36,
    padding: "0 8px",
    borderBottomWidth: 1,
    borderBottomStyle: "solid",
    borderBottomColor: colors.border,
  },
  tab: {
    position: "relative",
    display: "inline-flex",
    margin: 0,
    padding: "0 8px",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    color: colors.mutedForeground,
    backgroundColor: "transparent",
    borderWidth: 0,
    font: "inherit",
    fontSize: 12,
    fontWeight: 600,
    cursor: { default: "pointer", ":disabled": "default" },
    opacity: { default: 1, ":disabled": 0.45 },
    outline: { ":focus-visible": `2px solid ${colors.focus}` },
    outlineOffset: { ":focus-visible": -2 },
    "::after": {
      position: "absolute",
      right: 8,
      bottom: -1,
      left: 8,
      height: 2,
      backgroundColor: "transparent",
      content: "",
    },
  },
  tabSelected: {
    color: { default: colors.foreground, [media.forcedColors]: "HighlightText" },
    backgroundColor: { default: "transparent", [media.forcedColors]: "Highlight" },
    "::after": {
      backgroundColor: colors.primary,
    },
  },
  tabCount: {
    color: colors.mutedForeground,
    fontFamily: fonts.mono,
    fontSize: 9,
    fontVariantNumeric: "tabular-nums",
  },
  panel: {
    minHeight: 0,
    padding: "0 0 6px",
    overflow: "auto",
  },
  empty: {
    margin: 0,
    padding: "24px 16px",
    color: colors.mutedForeground,
    fontSize: 12,
    textAlign: "center",
  },
  notice: {
    minHeight: 0,
    maxHeight: "min(168px, 30dvh)",
    padding: "8px 8px 0",
    flex: "0 1 auto",
    overflow: "auto",
  },
  overflow: {
    position: "relative",
  },
  overflowSummary: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    listStyle: "none",
    cursor: "pointer",
    outline: { ":focus-visible": `2px solid ${colors.focus}` },
    outlineOffset: { ":focus-visible": -2 },
    "::-webkit-details-marker": { display: "none" },
  },
  overflowMenu: {
    position: "absolute",
    zIndex: 2,
    top: "calc(100% + 4px)",
    right: 0,
    width: "max-content",
    minWidth: 140,
    padding: 4,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: colors.border,
    borderRadius: radii.control,
    boxShadow: colors.shadow,
  },
  overflowAction: {
    display: "flex",
    width: "100%",
    minHeight: 32,
    margin: 0,
    padding: "0 8px",
    alignItems: "center",
    gap: 7,
    color: colors.mutedForeground,
    backgroundColor: "transparent",
    borderWidth: 0,
    borderRadius: radii.label,
    font: "inherit",
    fontSize: 12,
    cursor: { default: "pointer", ":disabled": "default" },
    opacity: { default: 1, ":disabled": 0.48 },
    outline: { ":focus-visible": `2px solid ${colors.focus}` },
    outlineOffset: { ":focus-visible": -2 },
  },
  overflowDanger: {
    color: {
      default: colors.mutedForeground,
      ":focus-visible": colors.destructive,
      ":not(:disabled):hover": colors.destructive,
    },
    backgroundColor: {
      default: "transparent",
      ":focus-visible": colors.destructiveSoft,
      ":not(:disabled):hover": colors.destructiveSoft,
    },
  },
});
