import * as stylex from "@stylexjs/stylex";

import { colors, fonts, media, motion } from "../../styles/tokens.stylex";

export const dockStyles = stylex.create({
  dock: {
    position: "fixed",
    zIndex: 10,
    top: 0,
    left: 0,
    display: "flex",
    width: "max-content",
    maxWidth: "calc(var(--ml-dock-viewport-width, 100vw) - 24px)",
    justifyContent: "center",
    pointerEvents: "none",
  },
  surface: {
    position: "relative",
    isolation: "isolate",
    display: "flex",
    alignItems: "center",
    color: colors.foreground,
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: "transparent",
    pointerEvents: "auto",
    "::before": {
      position: "absolute",
      zIndex: -1,
      inset: -1,
      borderWidth: 1,
      borderStyle: "solid",
      borderColor: { default: colors.border, [media.forcedColors]: "Highlight" },
      borderRadius: "inherit",
      backgroundColor: colors.surface,
      boxShadow: colors.shadow,
      transformOrigin: "top left",
      pointerEvents: "none",
      content: "",
      transitionProperty: "background-color",
      transitionDuration: { default: "140ms", [media.reducedMotion]: "0ms" },
      transitionTimingFunction: motion.ease,
    },
  },
  bar: {
    minHeight: { default: 42, [media.coarsePointer]: 44 },
    maxWidth: "100%",
    flexWrap: "wrap",
    padding: 4,
    gap: 2,
    borderRadius: 12,
  },
  action: {
    display: "inline-flex",
    height: { default: 32, [media.coarsePointer]: 36 },
    minHeight: { default: 32, [media.coarsePointer]: 44 },
    padding: "0 10px",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    color: "inherit",
    backgroundColor: {
      default: "transparent",
      [media.hover]: { ":not(:disabled):hover": colors.hover },
    },
    borderRadius: 8,
    fontSize: 14,
    fontWeight: 400,
    lineHeight: 1.4,
    whiteSpace: "nowrap",
    opacity: { default: 1, ":disabled": 0.42 },
    transitionProperty: "background-color, color, box-shadow",
    transitionDuration: { default: "140ms", [media.reducedMotion]: "0ms" },
    transitionTimingFunction: motion.ease,
  },
  dragHandle: {
    touchAction: "none",
    userSelect: "none",
    cursor: { default: "grab", ":active": "grabbing" },
  },
  grip: {
    width: 24,
    padding: 0,
    color: colors.mutedForeground,
  },
  select: {
    minWidth: 72,
  },
  selectArmed: {
    color: colors.foreground,
    backgroundColor: {
      default: `color-mix(in srgb, ${colors.primary} 10%, ${colors.surface})`,
      [media.hover]: {
        ":hover": `color-mix(in srgb, ${colors.primary} 15%, ${colors.surface})`,
      },
    },
    boxShadow: `inset 0 0 0 1px color-mix(in srgb, ${colors.primary} 20%, transparent)`,
  },
  selectIconArmed: {
    color: colors.primary,
  },
  shortcut: {
    display: "inline-flex",
    minWidth: 25,
    height: 18,
    marginLeft: 4,
    padding: "0 4px",
    alignItems: "center",
    justifyContent: "center",
    color: colors.mutedForeground,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: colors.border,
    borderRadius: 4,
    fontFamily: fonts.mono,
    fontSize: 10,
    fontWeight: 400,
    lineHeight: 1,
    textTransform: "lowercase",
  },
  selections: {
    minWidth: 48,
  },
  count: {
    display: "inline-flex",
    minWidth: 18,
    height: 18,
    padding: "0 4px",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.hover,
    borderRadius: 4,
    fontFamily: fonts.mono,
    fontSize: 10,
    fontWeight: 600,
    fontVariantNumeric: "tabular-nums",
  },
  icon: {
    width: 32,
    padding: 0,
    color: colors.mutedForeground,
  },
  separator: {
    width: 1,
    height: 14,
    margin: "0 1px",
    backgroundColor: colors.border,
  },
  tab: {
    width: 44,
    minWidth: 44,
    height: 36,
    minHeight: 36,
    padding: 0,
    justifyContent: "center",
    borderRadius: 4,
    fontSize: 13,
    fontWeight: 500,
    lineHeight: 1,
    transform: "none",
    transitionDuration: { default: "140ms", [media.reducedMotion]: "0ms" },
    "::before": {
      borderColor: {
        default: "var(--slate-7, #cdced6)",
        [media.hover]: { ":hover": "var(--grass-7, #97cfaa)" },
      },
      backgroundColor: {
        default: "var(--background, #ffffff)",
        [media.hover]: { ":hover": "var(--grass-2, #f2fcf5)" },
      },
      boxShadow: {
        default:
          "var(--shadow-xs-solid, 1px 1px 0 0 rgb(128 128 128 / 40%), 0 0 2px rgb(128 128 128 / 20%))",
        ":active": "none",
      },
    },
  },
  collapsedGrip: {
    position: "absolute",
    top: "50%",
    left: -15,
    display: "inline-flex",
    width: 14,
    height: 24,
    alignItems: "center",
    justifyContent: "center",
    color: {
      default: colors.mutedForeground,
      [media.hover]: { ":hover": "var(--grass-11, #2a7e3b)" },
      [media.forcedColors]: "CanvasText",
    },
    opacity: 0.64,
    pointerEvents: "auto",
    transform: "translateY(-50%)",
    transitionProperty: "color, opacity",
    transitionDuration: { default: "140ms", [media.reducedMotion]: "0ms" },
    transitionTimingFunction: motion.ease,
  },
  badge: {
    position: "absolute",
    top: -7,
    right: -7,
    display: "inline-flex",
    minWidth: 18,
    height: 18,
    padding: "0 4px",
    alignItems: "center",
    justifyContent: "center",
    color: colors.onPrimary,
    backgroundColor: colors.primaryHover,
    borderWidth: 2,
    borderStyle: "solid",
    borderColor: colors.surface,
    borderRadius: 999,
    boxShadow: "0 1px 2px rgb(15 23 42 / 18%)",
    fontFamily: fonts.mono,
    fontSize: 9,
    fontWeight: 600,
    fontVariantNumeric: "tabular-nums",
    lineHeight: 1,
  },
  sheetStack: {
    position: { default: "absolute", [media.mobile]: "fixed" },
    zIndex: 2,
    right: { default: "auto", [media.mobile]: 12 },
    bottom: {
      default: "calc(100% + 8px)",
      [media.mobile]: "max(64px, calc(env(safe-area-inset-bottom) + 56px))",
    },
    left: { default: "calc(50% - 184px)", [media.mobile]: 12 },
    width: { default: "min(368px, calc(100vw - 24px))", [media.mobile]: "auto" },
    maxHeight: { default: "min(520px, calc(100dvh - 92px))", [media.mobile]: "min(70dvh, 520px)" },
    pointerEvents: "none",
  },
});

export const logoStyles = stylex.create({
  root: {
    display: "grid",
    width: 28,
    height: 28,
    placeItems: "center",
  },
  image: {
    display: "block",
    gridArea: "1 / 1",
    width: 28,
    height: 28,
  },
  hidden: {
    display: "none",
  },
});
